repos:
  - repo: local
    hooks:
      - id: fix-ptbr-accents
        name: Fix pt-BR accents
        entry: python scripts/fix-ptbr-accents.py
        language: system
        types: [file]
        files: \.(tsx?|md)$
        pass_filenames: false
